baseurl: "https://cardinalby.github.io/blog"
title: Tech grumbling
theme: ghostwriter
languageCode: en-us
copyright: cardinalby
disqusShortname: https-cardinalby-github-io-blog
googleAnalytics: G-S1HYRNQV86
pygmentsUseClasses: true
pygmentsCodefences: true
paginate: 2147483647

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: cardinalby
  profile: "https://github.com/cardinalby"

taxonomies:
  tag: tags
  series: series

params:
  mainSections:
    - post
  intro: true
  headline: Tech grumbling
  description: A software engineer grumbling about the technologies he hates the least
  github: "https://github.com/cardinalby"
  linkedin: "https://www.linkedin.com/in/sergey-borodin/"
  stackoverflow: "https://stackoverflow.com/users/1180397/cardinal"
  opengraph: true
  rss: true
  dateFormat: "Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

#permalinks:
#  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /page/about/
      weight: 4
